const projects = () => {
  return [
    "",
    "  🚀 FEATURED PROJECTS",
    "  ═══════════════════════════════════",
    "",
    "  ┌─ Valura.ai ─────────────────────────────",
    "  │ AI-powered fintech platform",
    "  │ Stack: React Native • Node.js • MongoDB • AWS",
    "  │ https://valura.ai",
    "  └─────────────────────────────────────────",
    "",
    "  ┌─ Groww Trading Bot ─────────────────────",
    "  │ Quantitative trading system",
    "  │ Stack: Python • APIs • NLP",
    "  │ https://github.com/yashXc0des",
    "  └─────────────────────────────────────────",
    "",
    "  ┌─ School ERP System ─────────────────────",
    "  │ Full-scale ERP for 10,000+ students",
    "  │ Stack: Flutter • Laravel • MySQL",
    "  │ https://github.com/yashXc0des",
    "  └─────────────────────────────────────────",
    "",
    "  ┌─ Digital Agreement System ──────────────",
    "  │ Secure digital signing platform",
    "  │ Stack: Flutter • Firebase • Cloudflare R2",
    "  │ https://github.com/yashXc0des",
    "  └─────────────────────────────────────────",
    "",
    "  ┌─ Polymarket Prediction Bot ─────────────",
    "  │ NLP-driven autonomous prediction bot",
    "  │ Stack: Python • NLP • Data Engineering",
    "  │ https://github.com/yashXc0des",
    "  └─────────────────────────────────────────",
    "",
  ];
};

export default projects;
